# Generated by Django 5.0.9 on 2024-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entry_fee',
            field=models.PositiveIntegerField(default=1, help_text='Number of tickets required to enter'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes',
            field=models.TextField(blank=True, help_text='Tournament prizes and rewards'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, help_text='Detailed tournament rules and guidelines'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(help_text='Tournament description'),
        ),
    ]
