# Generated by Django 5.0.9 on 2024-11-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_entry_fee_tournament_prizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videosubmission',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
