# Generated by Django 5.0.9 on 2024-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_views_count_videosubmission_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured tournaments will be highlighted'),
        ),
    ]
