# Generated by Django 5.0.9 on 2024-12-08 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_username', 'Inappropriate username'), ('stolen_content', 'Stolen content'), ('adult_content', 'Nudity/Adult content'), ('racist', 'Racist'), ('promoting_products', 'Promoting products'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(help_text='Additional details about the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reports', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tournament.videosubmission')),
            ],
            options={
                'unique_together': {('reporter', 'video')},
            },
        ),
    ]
