# Generated by Django 5.0.9 on 2025-03-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_videoreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active_group_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of active groups created from this tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_name',
            field=models.CharField(blank=True, help_text="Group identifier (e.g., 'A', 'B', 'C')", max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_repeating',
            field=models.BooleanField(default=False, help_text='If true, new groups will be created when this tournament fills up'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='parent_tournament',
            field=models.ForeignKey(blank=True, help_text='Parent tournament for generated groups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tournaments', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Optional for repeating tournaments that end when filled', null=True),
        ),
    ]
