# Generated by Django 5.0.9 on 2025-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_active_group_count_tournament_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_showcase',
            field=models.BooleanField(default=False, help_text='Show this tournament in public showcase carousels'),
        ),
    ]
