# Generated by Django 5.0.9 on 2024-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time_login',
            field=models.BooleanField(default=True, help_text="Indicates if this is the user's first time logging in", verbose_name='First Time Login'),
        ),
    ]
