http:
  routers:
    web-secure-router:
      rule: "Host(`pro.lololympics.com`)"
      entryPoints:
        - web-secure
      service: django
      tls: {}

    flower-secure-router:
      rule: "Host(`pro.lololympics.com`) && PathPrefix(`/flower`)"
      entryPoints:
        - flower
      service: flower
      tls: {}

  services:
    django:
      loadBalancer:
        servers:
          - url: "http://django:5000"

    flower:
      loadBalancer:
        servers:
          - url: "http://flower:5555"