http:
  middlewares:
    cors-config:
      headers:
        accessControlAllowOriginList:
          - "https://laughterolympics.com"
          - "https://www.laughterolympics.com"
          - "http://localhost:3000"
          - "https://localhost:3000"
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        accessControlAllowHeaders:
          - "accept"
          - "authorization"
          - "content-type"
          - "user-agent"
          - "x-csrftoken"
          - "origin"
        accessControlExposeHeaders:
          - "Content-Type"
          - "X-CSRFToken"
        accessControlAllowCredentials: true
        accessControlMaxAge: 3600
        addVaryHeader: true

  routers:
    web-secure-router:
      rule: "Host(`prod.lololympics.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - cors-config
      service: django
      tls:
        certResolver: letsencrypt

  services:
    django:
      loadBalancer:
        servers:
          - url: "http://django:5000"