http:
  routers:
    acme-router:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: noop
      priority: 100

    web-secure-router:
      rule: "{{ env `TRAEFIK_DOMAIN_RULE` }}"
      entryPoints:
        - web-secure
      middlewares:
        - cors-headers
      service: django
      tls:
        certResolver: letsencrypt

    flower-secure-router:
      rule: "{{ env `TRAEFIK_FLOWER_DOMAIN_RULE` }}"
      entryPoints:
        - flower
      middlewares:
        - cors-headers
      service: flower
      tls:
        certResolver: letsencrypt

  middlewares:
    cors-headers:
      headers:
        accessControlAllowOrigin: "https://laughterolympics.com"
        accessControlAllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
        accessControlAllowHeaders: "*"
        accessControlAllowCredentials: "true"
        accessControlMaxAge: "100"
        addVaryHeader: "true"

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.0.2.0:80

    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555