http:
  routers:
    acme-router:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: noop
      priority: 100

    web-secure-router:
      rule: "{{ env `TRAEFIK_DOMAIN_RULE` }}"
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
      service: django
      tls:
        certResolver: letsencrypt

    flower-secure-router:
      rule: "{{ env `TRAEFIK_FLOWER_DOMAIN_RULE` }}"
      entryPoints:
        - flower
      service: flower
      tls:
        certResolver: letsencrypt

  middlewares:
    security-headers:
      headers:
        hostsProxyHeaders:
          - "X-CSRFToken"
        customResponseHeaders:
          Access-Control-Allow-Origin: "https://laughterolympics.com"
          Access-Control-Allow-Methods: "GET,POST,PUT,DELETE,OPTIONS"
          Access-Control-Allow-Headers: "Origin,Content-Type,Accept,Authorization,X-CSRF-Token"
          Access-Control-Allow-Credentials: "true"
          Access-Control-Max-Age: "3600"

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.0.2.0:80

    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555