log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

  flower:
    address: ":5555"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "pantelisa1995@gmail.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true