log:
  level: DEBUG

entryPoints:
  web:
    address: ':80'
    http:
      middlewares:
        - cors@file
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'
    http:
      middlewares:
        - cors@file
      tls:
        certResolver: letsencrypt

  flower:
    address: ':5555'
    http:
      middlewares:
        - cors@file
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'pantelisa1995@gmail.com'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  middlewares:
    cors:
      headers:
        accessControlAllowOrigin: "https://laughterolympics.com"
        accessControlAllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
        accessControlAllowHeaders: "*"
        accessControlAllowCredentials: "true"
        accessControlMaxAge: "100"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true